services:
  - type: web
    name: passpad
    env: node
    plan: free
    buildCommand: npm install
    startCommand: npm start
    envVars:
      - key: APP_SECRET
        generateValue: true
      - key: MAX_UPLOAD_BYTES
        value: 26214400
